# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'AutolayoutBestPractice' do
	pod 'Masonry'
	pod 'SDWebImage'
end

target 'AutolayoutBestPracticeTests' do
end

